### ISSUE TITLE
Unable to send messages on chat service on newly opened browser

### ISSUE THREAD

**Issue by blimyj** [CS3219-AY2223S1/cs3219-project-ay2223s1-g2#16]
Steps to reproduce:

1. Close all instances of browser. (Quit browser if on mac)
2. Launch two instances of browser (one in normal browsing, other in private/incognito)
3. Log in as different users (on both browsers)
4. Find match (on both browsers)
5. Attempt to chat.
6. Message can neither be sent nor received.

**Comment by howardwhw2** [comment]
Bug should be solved with yesterday's commit
